### ISSUE TITLE
Unable to push branch to CSE-NMIT

### ISSUE THREAD

**Issue by vilas1999** [CSE-NMIT/OOPS#1]
`remote: Permission to CSE-NMIT/OOPS.git denied to vilas1999.
fatal: unable to access 'https://github.com/CSE-NMIT/OOPS.git/': The requested URL returned error: 403`

It says permission denied even after managing credentials. Is anyone else facing same issue?

**Comment by sribs** [comment]
You cannot push directly to master. Follow as per what ``` README.md ``` instructs

**Comment by avinash-rath** [comment]
@sribs It's not that. The permissions have been denied to push any branch to the repository.
So we're unable to push our branch as instructed.

**Comment by sribs** [comment]
can we have a session and one of you can help your other friends. This is my skype id ``` sriharsha.bs@outlook.com ```

**Comment by sribs** [comment]
Please follow the below guidance and add rest of your friends as well

**Comment by sribs** [comment]
can @CSENMIT , @vilas1999 , @avinash-rath  or @AkankshaMS add the rest of the people to @CSE-NMIT/oops-ds-algo team and then members will be having write access

Once you add rest of the members, you can close the issue

**Comment by vilas1999** [comment]
Added everyone to @CSE-NMIT/oops-ds-algo

**Comment by CSENMIT** [comment]
Yes
