### ISSUE TITLE
Issue with test.sh | PWD not found

### ISSUE THREAD

**Issue by avinash-rath** [CSE-NMIT/OOPS#2]
![test_not_working](https://user-images.githubusercontent.com/39563984/80894200-ad909a80-8cf6-11ea-9fe0-65c4aeefa796.png)
Here's the screenshot of the execution.

**Comment by avinash-rath** [comment]
It required a few changes in `test.sh`
line 2 - Changed `PWD` to `pwd`
line 3 - Changed `"Assignments/$2"` to `"$(pwd)/Assignments/$2"`
line 22 - Changed `exit 0)` to `exit 0`

And my PC was running python3 so changed it from `python main.py` to `python3 main.py`

**Comment by sribs** [comment]
did you perform ``` git clone ``` as root ? send the output of ls -al of OOPS directory

**Comment by sribs** [comment]
Thanks! made the changes and submitted

**Comment by avinash-rath** [comment]
I'm sorry for the delay.
```
avinash@lenovo-budgie:~/Documents/OOPS$ ls -la
total 32
drwxr-xr-x  4 avinash avinash 4096 May  3 04:50 .
drwxr-xr-x 13 avinash avinash 4096 May  3 01:33 ..
drwxr-xr-x  3 avinash avinash 4096 May  3 01:33 Assignments
-rw-r--r--  1 avinash avinash  107 May  3 01:33 CODEOWNERS
drwxr-xr-x  8 avinash avinash 4096 May  3 05:00 .git
-rw-r--r--  1 avinash avinash  321 May  3 01:33 .gitignore
-rw-r--r--  1 avinash avinash 1294 May  3 01:33 README.md
-rwxrwxrw-  1 avinash avinash 1008 May  3 05:09 test.sh
```
