### ISSUE TITLE
Maintaining the order of output

### ISSUE THREAD

**Issue by avinash-rath** [CSE-NMIT/OOPS#4]
I had completed the implementation, here's the diff
```
10,11d9
< User2 owes User1: 620
< User3 owes User1: 1130
15a14
> User2 owes User1: 620
16a16
> User3 owes User1: 1130
```

I think it's only the order that has changed while printing it. Do we need to maintain the order while printing?

**Comment by avinash-rath** [comment]
Also, there's another issue with test.sh
```
Code Compile and Test
./test.sh: line 4: [Python: command not found
==================Testing==================
./test.sh: line 18: [-f: command not found
```

**Comment by avinash-rath** [comment]
Oh, this is silly. Shell requires whitespace to be around `[` and `]` 
So there are a couple more changes in
line 18: `if [-f $WD/final]` to `if [ -f $WD/final ]`
line 20: `if [-s $WD/final]` to `if [ -s $WD/final ]`

**Comment by sribs** [comment]
Yes,  it is required. Resolved test.sh Perform ``` git pull ```

However, I lift the restrictions for now. Go ahead and raise a PR

**Comment by avinash-rath** [comment]
> I had completed the implementation, here's the diff
> 
> ```
> 10,11d9
> < User2 owes User1: 620
> < User3 owes User1: 1130
> 15a14
> > User2 owes User1: 620
> 16a16
> > User3 owes User1: 1130
> ```
> 
> I think it's only the order that has changed while printing it. Do we need to maintain the order while printing?

@sribs
